"""${message}

Revision ID: b7a89b1a55ec
Revises:
Create Date: 2026-09-28 18:36:50.723346

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b7a89b1a55ec"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
